### ISSUE TITLE
PDF schematic 

### ISSUE THREAD

**Issue by ilium007** [Hugoyhu/RP2040-Module-V2#1]
Would it be possible to get a PDF schematic for those who are trying to research on s as mobile device without KiCad?

**Comment by Hugoyhu** [comment]
Hello, certainly. I’ll upload in a few hours.

Hugo Hu

On Apr 19, 2021, at 7:06 AM, ilium007 ***@***.***> wrote:

﻿

Would it be possible to get a PDF schematic for those who are trying to research on s as mobile device without KiCad?

**Comment by ilium007** [comment]
Thanks!

**Comment by Hugoyhu** [comment]
Hi @ilium007, super sorry for the delay.

![image](https://user-images.githubusercontent.com/69009840/116102793-fdd9d880-a67c-11eb-9384-c55d2b63553e.png)

**Comment by ilium007** [comment]
So good. Thanks

**Comment by ilium007** [comment]
Do you have a part number for the crystal used?

**Comment by Hugoyhu** [comment]
oh wait actually crap I screwed up on the crystal one sec that's supposed to have a built in cap

**Comment by Hugoyhu** [comment]
<img width="1534" alt="Screen Shot 2021-04-29 at 3 21 26 PM" src="https://user-images.githubusercontent.com/69009840/116606656-07727300-a8ff-11eb-9cfe-70e925324b62.png">
Hello again!

Terribly sorry for the delay again.

Here is the new schematic

The crystal used is a 12Mhz 2.5x2.0mm crystal with built in caps

https://www.mouser.com/datasheet/2/122/ECX_2236-15751.pdf

this one should work

**Comment by ilium007** [comment]
Thanks!
